### ISSUE TITLE
非剿灭代理卡情况下的超时问题

### ISSUE THREAD

**Issue by Siss4uer** [DLmaster361/AUTO_MAA#1]
当使用非剿灭代理卡时，maa使用代理作战的方式刷剿灭，maa无日志返回，判定超时无法完成任务从而关闭进程，导致死循环
![image](https://github.com/DLmaster361/AUTO_MAA/assets/107382028/9d459509-b9cf-4ca6-a924-66d5fa9b7908)

**Comment by DLmaster361** [comment]
感谢您的反馈，这个问题将在五月一号更新的v2.1.4中修复（作者是高三考生，没有精力维护，请见谅）。
在v2.1.4发布前，您可以通过将LOGXLEN扩大为180以临时规避这个问题。
requirements.txt暂时缺失，您可以通过询问通义千问获取完整的依赖列表。
当然，我更欢迎您自行更正代码，感谢您对本项目的支持与贡献。
