### ISSUE TITLE
在Windows深色模式下，新建用户界面无法看清

### ISSUE THREAD

**Issue by ClozyA** [DLmaster361/AUTO_MAA#10]
https://github.com/user-attachments/assets/0a6c702e-8b9a-482d-ac72-22179b9fa7c0

![image](https://github.com/user-attachments/assets/5342fe6a-ae3f-41be-b3cd-3797875f1e43)

**Comment by DLmaster361** [comment]
将在一周内修复，感谢反馈

**Comment by DLmaster361** [comment]
已初步完成修复，可通过更新器获取最新版本。若问题未消失，请反馈。

**Comment by ClozyA** [comment]
感谢，问题应该是修复了，暂时未发现其他问题

DLmaster ***@***.***> 于2024年12月4日周三 15:06写道：
