### ISSUE TITLE
数据加密是出于什么样的考虑？

### ISSUE THREAD

**Issue by Zrief** [DLmaster361/AUTO_MAA#2]
程序似乎完全在本地运行，似乎没有加密的需求，且加密导致程序逻辑更复杂。数据储存在文本文件或者Excel文件中似乎更方便管理者修改。

**Comment by DLmaster361** [comment]
您好，感谢您对数据安全性的关切。
关于数据加密，尽管这只是一个本地运行的程序，但由于其可能被用于集中存储管理用户密码，进行加密保护是必须的。在明日方舟尚未拥有多账号功能的时候，MAA项目其实完全可以凭借图像识别和模拟按键实现手动登录。但他们没有开发相关功能，除了这是对代肝的重大利好，与MAA的项目初衷相违背外，还有一个重要原因就是密码泄露风险。MAA软件除了软件更新功能需要联网，其它功能实际上都是本地运行的。但由于MAA的开源属性，一旦存储用户密码，黑客完全可以通过源代码快速定位文件位置，窃取相关信息。这种入侵与盗取本地cookie的行为原理相同，不需要程序联网，只要电脑联网，就有实现窃取的可能。基于相同的考虑，AUTO_MAA提供了本地加密功能，即使本地文件泄露，算法全流程透明，仍很难解析出用户密码。由此造成的困扰，我深表歉意。在后续更新中，我会在开发文档中加入加密模型图示，但这需要时间。您在使用时，可以不深究加密解密的算法细节，因为我已经将加密解密用函数模块化，完全可以直接使用。
关于数据存储，目前SQLite3的方案确实可拓展性较低，之后会考虑更换存储库。但使用TXT、EXCEL暂时不会考虑，因为未来会进行图形化界面开发，增强易用性。
