### ISSUE TITLE
在密钥加密这一步卡住

### ISSUE THREAD

**Issue by heziziziscool** [DLmaster361/AUTO_MAA#3]
在第一次运行`manage.py`设置密钥后，程序会直接卡住，并未生成相应的密钥。
查看源代码后，应该是没有bug的，是什么原因造成的呢？

**Comment by DLmaster361** [comment]
请检查data目录，在首次运行时目录下应存在一个空文件夹`key`，不应存在data.db

**Comment by heziziziscool** [comment]
> 请检查data目录，在首次运行时目录下应存在一个空文件夹`key`，不应存在data.db

删去后再次运行，这次在cmd中运行，结果还是一样输完密钥后，并没有生成key文件在data/key目录下。

**Comment by heziziziscool** [comment]
路径问题，修改路径后就好了

**Comment by DLmaster361** [comment]
请问这个路径具体指什么，是否是普遍问题？

**Comment by DLmaster361** [comment]
哦，原来关闭issues后不能回复啊。。。抱歉，新手

**Comment by heziziziscool** [comment]
> 哦，原来关闭issues后不能回复啊。。。抱歉，新手

没关系，我魔改了一下这个项目，在项目里加了~很多东西（但是很多是为了适配我的部分项目的做的），能pull上来不~

**Comment by DLmaster361** [comment]
哦，当然可以，你可以酌情考虑直接在原分支上提交或新建一个分支。

**Comment by DLmaster361** [comment]
另外，看到你随时关了issues，我欣慰地笑了

**Comment by DLmaster361** [comment]
我在你的仓库中没有看到魔改后的代码，就算是不在我这里提交分支，您也需要依据GPL开源您的代码哦。
emmm，我的意思是，把代码端上来让我学习学习！

**Comment by heziziziscool** [comment]
> 我在你的仓库中没有看到魔改后的代码，就算是不在我这里提交分支，您也需要依据GPL开源您的代码哦。 emmm，我的意思是，把代码端上来让我学习学习！

可能要等我中考后，把项目的部分隐私给处理了才能pull上来了，写得很乱，很多都是个性化代码XD，主要修改的功能：

- 把剿灭代理和日常代理给删了的`set_maa`，新增了一个方法来读写config。
- 在项目中集成了Nonebot，加了一个新的QQbot来推送完成通知，自助修改关卡。
- 对于在`run_maa`函数中处理超时逻辑进行了修改，修改为日志每生成一条间隔时间超过40min即即为超时。
- 对于`manage.py`中使用了一个`PrettyTable`包来进行输出用户信息。
- 在db文件中默认加了一项`QQ_id`以及两个备用关卡。
- 还有就是对于密钥生成以及检验进行了部分优化。
- 对于部分代码进行了优化（针对不符合`PEP8规范`）

大概就是这些，你看哪些需要Pull到项目上来，否则我将同步到仓库不会对具体功能做自定义修改以及适配`manage.py`。

**Comment by DLmaster361** [comment]
啊？中考生？我以为我这个高考生已经够离谱了！先全部提交到分支里吧，我看一下源代码，因为3.0要做GUI，现在也说不好该怎么迭代

**Comment by heziziziscool** [comment]
> 啊？中考生？我以为我这个高考生已经够离谱了！先全部提交到分支里吧，我看一下源代码，因为3.0要做GUI，现在也说不好该怎么迭代

整个项目思路是好的，毕竟MAA官方的Python接口年久失修，很多GUI的功能都没有，但是在处理模拟器多开会很麻烦…？GUI您打算是用C#直接对接Python/Python原生QT5/Fastapi+web开发封装？

以我来看Fastapi+web开发封装这个最好，后续二开也会很方便开发者。只需要用FastApi封装一下manage.py的很多方法即可，不需要重构。

对了，用pyinstaller打包的exe，在我的服务器上运行是有问题的，而且因为这个导致程序主目录特别乱，后续的热更新也难以实现；建议提高AUTO_MAA.py的windows权重，不然在实际使用中容易进程出现卡死~(双击回车键又OK的情况)~

以及在使用的过程中会出现很多次“模拟器关闭失败”日志后，脚本没有关闭模拟器的情况。具体问题还是需要等待我有时间了复现。

大概就是以上的一些已知的bug。

**Comment by heziziziscool** [comment]
而且目前对于MAA是否完成的判定有些死板了，在state下存放文件是否有BEGIN和RUNNING文件来判定是否允许，后续是否可以考虑使用redis队列来更灵活地管理任务状态，不再依赖于文件系统来存储和判定任务状态。

**Comment by DLmaster361** [comment]
关于项目思路：额，我其实根本不知道MAA有什么Python接口（天知道，我压根没学过这东西），所以算是歪打正着吧。。。

关于GUI开发：我将使用tinkter进行重构，本项目的第一个版本号只会在出现重构或更改数据库时进行变动，3.0版本按开发计划是需要在GUI开发的同时进行重构的。因为这个项目确实规模不大，而且我自己也暂时没有提供API的想法，主要是个人能力有限，确实没办法进行这种开发。等大学学习后，我会再次重构4.0，预计会添加图像识别等能力，实现对MAA完成判定的优化，同时可能会修改成Fastapi+web开发封装。

关于pyinstaller打包：很抱歉，我目前没有使用服务器，也缺乏相关经验，这个问题可能需要您给出较为详细的指导，我才能知道如何修改。

关于state：等我学习一下redis队列是什么

关于模拟器关闭：在我的运行环境（win）,多数情况下可以正常关闭。请问您服务器使用的系统是什么？如果是Linux，指令中是否添加了表示`中止所有子进程`的参数？

_另外，真的不考虑重新提一个Issues吗？这个Issues底下的讨论已经完全偏题了……_

**Comment by DLmaster361** [comment]
关于中考：如果你是应届考生的话，祝考试大捷！

**Comment by DLmaster361** [comment]
纠正：项目改用pyside6进行开发
