### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by Zrief** [DLmaster361/AUTO_MAA#7]
1. “自定义基建”不明确应该输入的内容，可以改成“自定义基建文件路径”或者“基建文件路径”
2. 在maa的gui.json文件中，"Start.ClientType"可以选择"Bilibili","Official"。希望对账号加个客户端类型。虽然b服切换目前有大问题，但这样至少能开一个b服，比没有强。

**Comment by DLmaster361** [comment]
感谢您的建议，这两项改进将在下个版本实现

**Comment by DLmaster361** [comment]
可否告诉我，B服时切换是识别用户名还是手机号？抑或暂不支持识别切换账号？

**Comment by Zrief** [comment]
> 可否告诉我，B服时切换是识别用户名还是手机号？抑或暂不支持识别切换账号？

目前从https://maa.plus/docs/zh-cn/manual/introduction/startup.html来看是用户名识别。

**Comment by DLmaster361** [comment]
经确认，MAA项目组可能将完全移除对B服账号切换的支持。我们暂拟定以模拟器多开的方法曲线救国。
