### ISSUE TITLE
tips的蓝字无法跳转至github+正常退出窗口显示停止工作

### ISSUE THREAD

**Issue by oEthan2333o** [DLmaster361/AUTO_MAA#9]
tips的蓝字无法跳转至github+正常退出窗口显示停止工作

Uploading 2024-11-09_11-47-04.mp4…

**Comment by oEthan2333o** [comment]
https://github.com/user-attachments/assets/80d6277f-207d-48e3-ad2b-6b497dd6726d

**Comment by DLmaster361** [comment]
正常退出窗口显示停止工作通常在什么时候出现？是每次关闭程序都会出现吗？

**Comment by oEthan2333o** [comment]
我的体验是无论在什么样的情况下关闭窗口必弹

**Comment by oEthan2333o** [comment]
> 正常退出窗口显示停止工作通常在什么时候出现？是每次关闭程序都会出现吗？

我的体验是无论在什么样的情况下关闭窗口必弹
